name: recipeapplication
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2   
  http: ^0.13.3
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4
  firebase_storage: ^8.0.3
  firebase_auth: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: "1.1.0"

flutter:

  uses-material-design: true

  #assets:
    #- images\logo.png


  fonts:
    - family: Overpass
      fonts:
       - asset: assets/fonts/overpass-bold.otf
    - family: OverpassRegular
      fonts:
        - asset: assets/fonts/overpass-regular.otf
